<script lang="ts">
    let brightnessScale = $state(1);
    let lutValueCount = $state(2);

    const FLOATING_POINT_DIGITS = 4;

    type LUTValue = [number, number, number, number];

    let lutValues: LUTValue[] = $derived.by(calculateLutValues);
    let lutData: string = $derived.by(generateLutData);

    function calculateLutValues() {
        let values = [] as LUTValue[];
        for (let i = 0; i < lutValueCount; i++) {
            const from = i / (lutValueCount - 1);
            const toR = from * brightnessScale;
            const toG = from * brightnessScale;
            const toB = from * brightnessScale;
            values.push([from, toR, toG, toB]);
        }
        return values;
    }

    function generateLutData() {
        return `# Generated by Demo LUT Generator
# Brightness Scale: ${brightnessScale}
LUT_1D_SIZE ${lutValueCount}
LUT_1D_INPUT_RANGE 0.0 1.0
${lutValues
    .map((value) =>
        value
            .slice(1)
            .map((v) => v.toFixed(FLOATING_POINT_DIGITS))
            .join(" ")
    )
    .join("\n")}
`;
    }

    function download() {
        const data = generateLutData();
        const blob = new Blob([data], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `lut_${brightnessScale}.cube`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
</script>

<div class="row">
    <div class="col">
        <h3>LUT Config</h3>
        <div class="row mb-3">
            <label for="inputBrightnessScale" class="col-sm-4 col-form-label">Brightness Scale: {brightnessScale}</label>
            <div class="col-sm-8 pt-2">
                <input type="range" class="form-range" id="inputBrightnessScale" min="0" max="1" step="0.001" bind:value={brightnessScale} />
            </div>
        </div>

        <hr />

        <div class="d-flex justify-content-between mb-3">
            <h3>LUT Preview</h3>
            <button class="btn btn-outline-primary" onclick={download}>Download</button>
        </div>
        <div class="row mb-3">
            <label for="inputBrightnessScale" class="col-sm-2 col-form-label">Number of Values</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="inputBrightnessScale" min="2" max="65535" step="1" bind:value={lutValueCount} />
            </div>
        </div>

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>From</th>
                        <th class="table-danger">To R</th>
                        <th class="table-success">To G</th>
                        <th class="table-primary">To B</th>
                    </tr>
                </thead>
                <tbody>
                    {#each lutValues as lutValue}
                        <tr>
                            <td>{lutValue[0].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-danger">{lutValue[1].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-success">{lutValue[2].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-primary">{lutValue[3].toFixed(FLOATING_POINT_DIGITS)}</td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
        <pre class="border rounded p-2">{lutData}</pre>
    </div>
    <div class="col border-start"></div>
</div>
