<script lang="ts">
    import LineChart from "./LineChart.svelte";

    const parameters = [
        { name: "Brigtness Scale", min: 0, max: 1, step: 0.001, calc: (input: number, value: number) => value * input, defaultValue: 1 },
        { name: "Brightness Offset", min: 0, max: 1, step: 0.001, calc: (input: number, value: number) => value + input, defaultValue: 0 },
        { name: "Gamma", min: 0, max: 3, step: 0.001, calc: (input: number, value: number) => Math.pow(value, input), defaultValue: 1 },
        { name: "Contrast", min: -3, max: 3, step: 0.001, calc: (input: number, value: number) => (value - 0.5) * input + 0.5, defaultValue: 1 },
    ];

    const INTERPOLATION_MODES = ["Linear", "Cubic", "Nearest Neighbour"] as const;
    type InterpolationMode = (typeof INTERPOLATION_MODES)[number];
    let interpolationModes: InterpolationMode[] = $state([INTERPOLATION_MODES[0]]);

    const values = $state(Object.fromEntries(parameters.map((parameter) => [parameter.name, parameter.defaultValue])));

    let lutValueCount = $state(32);
    let originalImage: HTMLImageElement | null = null;
    let originalImageUrl: string | null = $state(null);

    const FLOATING_POINT_DIGITS = 4;

    type LUTValue = [number, number, number, number];

    let lutValues: LUTValue[] = $derived.by(calculateLutValues);
    let lutData: string = $derived.by(generateLutData);
    let lutImageUrl: string = $derived.by(applyLUT);

    function calculateLutValues() {
        let resultValues = [] as LUTValue[];
        for (let i = 0; i < lutValueCount; i++) {
            const from = i / (lutValueCount - 1);
            const tos = [from, from, from];
            for (let toIndex = 0; toIndex < 3; toIndex++) {
                for (let j = 0; j < parameters.length; j++) {
                    const parameter = parameters[j];
                    tos[toIndex] = parameter.calc(values[parameter.name], tos[toIndex]);
                }
            }
            resultValues.push([from, tos[0], tos[1], tos[2]]);
        }
        return resultValues;
    }

    function generateLutData() {
        return `# Generated by Demo LUT Generator
${parameters.map((parameter) => `# ${parameter.name}: ${values[parameter.name].toFixed(FLOATING_POINT_DIGITS)}`).join("\n")}
LUT_1D_SIZE ${lutValueCount}
LUT_1D_INPUT_RANGE 0.0 1.0
${lutValues
    .map((value) =>
        value
            .slice(1)
            .map((v) => v.toFixed(FLOATING_POINT_DIGITS))
            .join(" ")
    )
    .join("\n")}
`;
    }

    function download() {
        const data = generateLutData();
        const blob = new Blob([data], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `demo_lut_${new Date().toISOString()}.cube`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    function loadImage() {
        const input = document.createElement("input");
        input.type = "file";
        input.accept = "image/*";
        input.onchange = async (event) => {
            const file = (event.target as HTMLInputElement).files?.[0];
            if (file) {
                const url = URL.createObjectURL(file);
                originalImage = new Image();
                originalImage.src = url;
                originalImage.onload = () => {
                    lutImageUrl = applyLUT();
                    originalImageUrl = url;
                };
                originalImage.onerror = () => {
                    console.error("Error loading image");
                };
            }
        };
        input.click();
    }

    function interpolateLUT(value: number, channelIndex: number): number {
        let lower = lutValues[0];
        let upper = lutValues[lutValues.length - 1];

        for (let i = 0; i < lutValues.length - 1; i++) {
            if (lutValues[i][0] <= value && value <= lutValues[i + 1][0]) {
                lower = lutValues[i];
                upper = lutValues[i + 1];
                break;
            }
        }

        const t = (value - lower[0]) / (upper[0] - lower[0]);
        return lower[channelIndex] + t * (upper[channelIndex] - lower[channelIndex]);
    }

    function applyLUT(): string {
        if (!originalImage) return "";
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");
        if (!ctx) return "";

        canvas.width = originalImage.width;
        canvas.height = originalImage.height;
        ctx.drawImage(originalImage, 0, 0);

        const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
        const data = imageData.data;

        for (let i = 0; i < data.length; i += 4) {
            const r = data[i] / 255;
            const g = data[i + 1] / 255;
            const b = data[i + 2] / 255;

            data[i] = Math.min(interpolateLUT(r, 1) * 255, 255);
            data[i + 1] = Math.min(interpolateLUT(g, 2) * 255, 255);
            data[i + 2] = Math.min(interpolateLUT(b, 3) * 255, 255);
        }

        ctx.putImageData(imageData, 0, 0);
        return canvas.toDataURL();
    }

    function resetAll() {
        for (const parameter of parameters) {
            values[parameter.name] = parameter.defaultValue;
        }
    }
</script>

<div class="row">
    <div class="col">
        <div class="table-resonsive">
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th colspan="3">
                            <h3>LUT Config</h3>
                        </th>
                        <th>
                            <button class="btn btn-outline-secondary" onclick={resetAll}>Reset</button>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {#each parameters as parameter}
                        <tr>
                            <td>
                                <label for={`input${parameter.name}`} class="">{parameter.name}</label>
                            </td>
                            <td>
                                <input type="range" class="form-range" id={`input${parameter.name}`} min={parameter.min} max={parameter.max} step={parameter.step} bind:value={values[parameter.name]} />
                            </td>
                            <td>
                                {values[parameter.name].toFixed(FLOATING_POINT_DIGITS)}
                            </td>
                            <td>
                                <button class="btn btn-outline-secondary" onclick={() => (values[parameter.name] = parameter.defaultValue)}>Reset</button>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>

        <hr />

        <div class="d-flex justify-content-between mb-3">
            <h3>LUT Preview</h3>
            <button class="btn btn-outline-primary" onclick={download}>Download</button>
        </div>
        <div class="row mb-3">
            <label for="inputBrightnessScale" class="col-sm-2 col-form-label">Number of Values</label>
            <div class="col-sm-10">
                <input type="number" class="form-control" id="inputBrightnessScale" min="2" max="65535" step="1" bind:value={lutValueCount} />
            </div>
        </div>

        <div class="table-responsive max-h-300 mb-3">
            <table class="table">
                <thead class="position-sticky top-0 bg-light">
                    <tr>
                        <th>From</th>
                        <th class="table-danger">To R</th>
                        <th class="table-success">To G</th>
                        <th class="table-primary">To B</th>
                    </tr>
                </thead>
                <tbody>
                    {#each lutValues as lutValue}
                        <tr>
                            <td>{lutValue[0].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-danger">{lutValue[1].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-success">{lutValue[2].toFixed(FLOATING_POINT_DIGITS)}</td>
                            <td class="table-primary">{lutValue[3].toFixed(FLOATING_POINT_DIGITS)}</td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
        <pre class="border rounded p-2 max-h-300">{lutData}</pre>
    </div>
    <div class="col border-start">
        <div class="d-flex justify-content-between">
            <h3>Image Preview</h3>
            <button class="btn btn-outline-secondary mb-3" onclick={loadImage}>Load Image</button>
        </div>
        <div>
            <div class="btn-group">
                {#each INTERPOLATION_MODES as mode}
                    <input type="checkbox" class="btn-check" name="interpolationMode" id={mode} autocomplete="off" bind:group={interpolationModes} value={mode} />
                    <label class="btn btn-outline-primary mb-3" for={mode}>{mode}</label>
                {/each}
            </div>
        </div>
        <div class="row">
            <LineChart
                datasets={[
                    {
                        label: "Reference",
                        data: [
                            { x: 0, y: 0 },
                            { x: 1, y: 1 },
                        ],
                        borderColor: "gray",
                        borderWidth: 1,
                        tension: 0,
                    },
                    ...interpolationModes.map((m) => ({
                        label: "LUT",
                        data: lutValues.map((value) => ({
                            x: value[0],
                            y: value[1],
                        })),
                        borderColor: m === "Linear" ? "orange" : m === "Cubic" ? "purple" : "pink",
                        borderWidth: 2,
                        tension: 0,
                        stepped: m === "Nearest Neighbour" ? ("middle" as const) : false,
                        cubicInterpolationMode: m === "Cubic" ? ("monotone" as const) : ("default" as const),
                    })),
                ]}
            />
        </div>
        <div class="row">
            {#if originalImageUrl}
                <div class="col">
                    <h5>Original Image</h5>
                    <img id="originalImage" class="img-fluid border" alt="Original" src={originalImageUrl} />
                </div>
                {#if lutImageUrl}
                    <div class="col">
                        <h5>Image with LUT</h5>
                        <img id="lutImage" class="img-fluid border" alt="with LUT" src={lutImageUrl} />
                    </div>
                {/if}
            {/if}
        </div>
    </div>
</div>

<style>
    .max-h-300 {
        max-height: 300px;
        overflow-y: auto;
    }
</style>
